### ISSUE TITLE
详细介绍一下如何部署你的开源项目

### ISSUE THREAD

**Issue by Miaoyww** [YUXUAN888/FSM3#3]
介绍一下你开发时的系统环境，使用的什么工具进行开发
SquareMinecraftLauncherCore项目在哪里可以找到你使用的版本

**Comment by David-Xian66** [comment]
？

**Comment by Miaoyww** [comment]
> ？

？

**Comment by David-Xian66** [comment]
那个不是要赞助吗？

**Comment by Miaoyww** [comment]
> 那个不是要赞助吗？

什么要赞助

**Comment by David-Xian66** [comment]
都用别人的框架是吧 （就我自己写核心是吧
![A8D6D5CC70464AD575DD32807F6BD0D5](https://user-images.githubusercontent.com/70191815/180214431-ffb8a7c8-172b-483f-aae5-f2e918079d8f.png)

**Comment by David-Xian66** [comment]
SquareMinecraftLauncherCore项目

**Comment by Miaoyww** [comment]
> SquareMinecraftLauncherCore项目

FMS3用的是赞助版的是吧，那就算了吧

**Comment by David-Xian66** [comment]
https://github.com/baibao132/SquareMinecraftLauncherCore

**Comment by YUXUAN888** [comment]
SquareMinecraftLauncherCore为合作开发，FSM3 目前使用的版本无法在互联网中找到

**Comment by David-Xian66** [comment]
对的（

**Comment by David-Xian66** [comment]
因为合作了 所以没花钱

**Comment by Miaoyww** [comment]
那就算了吧， @YUXUAN888 能说说你的部署时的环境不

**Comment by YUXUAN888** [comment]
.net framework4.6.2

**Comment by Miaoyww** [comment]
4.6.2的wpf应用吗？

**Comment by YUXUAN888** [comment]
是的

**Comment by Miaoyww** [comment]
好，屑屑你

**Comment by Miaoyww** [comment]
谢谢你

**Comment by Miaoyww** [comment]
(

**Comment by Miaoyww** [comment]
@YUXUAN888 可以把环境写到README中吗，方便其他人部署？顺便还有IDE和电脑配置说一下？（
