### ISSUE TITLE
问下MD文件中的这个东西是怎么做到的（API是啥

### ISSUE THREAD

**Issue by David-Xian66** [YUXUAN888/FSM3#4]
![截屏2022-07-21 20 43 19](https://user-images.githubusercontent.com/70191815/180216180-54efed65-13dc-4e63-b970-0c86932e884c.png)

**Comment by David-Xian66** [comment]
@YUXUAN888

**Comment by Miaoyww** [comment]
我来
https://repobeats.axiom.co/

**Comment by David-Xian66** [comment]
OK呀 谢谢 @Miaoywww

**Comment by David-Xian66** [comment]
这东西唯一缺点 就是那颜色 改不了（粉色我受不了
