### ISSUE TITLE
请问README里面那个图表是在哪做的呀

### ISSUE THREAD

**Issue by CatSayInk** [YUXUAN888/FSM3#6]
<img width="864" alt="CleanShot 2022-07-28 at 10 36 16@2x" src="https://user-images.githubusercontent.com/26319155/181408076-c986d6f7-e5ad-4360-ab0e-4ac34df5f839.png">

**Comment by David-Xian66** [comment]
这个问题我在前面的issue里问过

**Comment by David-Xian66** [comment]
https://github.com/YUXUAN888/FSM3/issues/4

**Comment by David-Xian66** [comment]
嗯自己看

**Comment by David-Xian66** [comment]
@CatSayInk

**Comment by CatSayInk** [comment]
> 嗯自己看

多谢
